[options]
work_mode = "sys"
library = "Phosh"
version = "0"
girs_directories = ["../../gir-files", "../../"]
min_cfg_version = "1"
external_libraries = [
   "GLib",
   "GObject",
   "Gio",
   "Gtk",
   "Gdk",
   "GdkPixbuf",
   "Pango",
   "Handy",
]

ignore = [
    "Phosh.Ambient",
    "Phosh.AppAuthPrompt",
    "Phosh.AppGrid",
    "Phosh.AppGridBaseButton",
    "Phosh.AppGridButton",
    "Phosh.AppGridFolderButton",
    "Phosh.AppListModel",
    "Phosh.AppTracker",
    "Phosh.Arrow",
    "Phosh.AudioDevice",
    "Phosh.AudioDeviceRow",
    "Phosh.AudioDevices",
    "Phosh.AudioSettings",
    "Phosh.Auth",
    "Phosh.AuthPromptOption",
    "Phosh.Background",
    "Phosh.BackgroundCache",
    "Phosh.BackgroundImage",
    "Phosh.BackgroundManager",
    "Phosh.BatteryInfo",
    "Phosh.BtInfo",
    "Phosh.BtManager",
    "Phosh.Call",
    "Phosh.CallNotification",
    "Phosh.CallsDBusCallsCallProxy",
    "Phosh.CallsDBusCallsCallSkeleton",
    "Phosh.CallsDBusObjectManagerClient",
    "Phosh.CallsDBusObjectProxy",
    "Phosh.CallsDBusObjectSkeleton",
    "Phosh.CallsManager",
    "Phosh.Clamp",
    "Phosh.ConnectivityInfo",
    "Phosh.DBusColorProxy",
    "Phosh.DBusColorSkeleton",
    "Phosh.DBusDisplayConfigProxy",
    "Phosh.DBusDisplayConfigSkeleton",
    "Phosh.DBusEndSessionDialogProxy",
    "Phosh.DBusEndSessionDialogSkeleton",
    "Phosh.DBusGnomeShellProxy",
    "Phosh.DBusGnomeShellSkeleton",
    "Phosh.DBusHostname1Proxy",
    "Phosh.DBusHostname1Skeleton",
    "Phosh.DBusImplPortalAccessProxy",
    "Phosh.DBusImplPortalAccessSkeleton",
    "Phosh.DBusImplPortalRequestProxy",
    "Phosh.DBusImplPortalRequestSkeleton",
    "Phosh.DBusLoginManagerProxy",
    "Phosh.DBusLoginManagerSkeleton",
    "Phosh.DBusLoginSessionProxy",
    "Phosh.DBusLoginSessionSkeleton",
    "Phosh.DBusMountOperationHandlerProxy",
    "Phosh.DBusMountOperationHandlerSkeleton",
    "Phosh.DBusNotification",
    "Phosh.DBusScreenSaverProxy",
    "Phosh.DBusScreenSaverSkeleton",
    "Phosh.DBusScreenshotProxy",
    "Phosh.DBusScreenshotSkeleton",
    "Phosh.DBusSensorProxyCompassProxy",
    "Phosh.DBusSensorProxyCompassSkeleton",
    "Phosh.DBusSensorProxyProxy",
    "Phosh.DBusSensorProxySkeleton",
    "Phosh.DBusSessionManagerProxy",
    "Phosh.DBusSessionManagerSkeleton",
    "Phosh.DockedInfo",
    "Phosh.DockedManager",
    "Phosh.DragSurface",
    "Phosh.EmergencyCallsManager",
    "Phosh.EmergencyCallsProxy",
    "Phosh.EmergencyCallsSkeleton",
    "Phosh.EmergencyContact",
    "Phosh.EmergencyContactRow",
    "Phosh.EmergencyMenu",
    "Phosh.EndSessionDialog",
    "Phosh.Fader",
    "Phosh.FadingLabel",
    "Phosh.FavoriteListModel",
    "Phosh.FeedbackInfo",
    "Phosh.FeedbackManager",
    "Phosh.FolderInfo",
    "Phosh.GeoClueDBusManagerProxy",
    "Phosh.GeoClueDBusManagerSkeleton",
    "Phosh.GeoClueDBusOrgFreedesktopGeoClue2AgentProxy",
    "Phosh.GeoClueDBusOrgFreedesktopGeoClue2AgentSkeleton",
    "Phosh.GnomeShellManager",
    "Phosh.GtkMountManager",
    "Phosh.GtkMountPrompt",
    "Phosh.Head",
    "Phosh.HksInfo",
    "Phosh.HksManager",
    "Phosh.Home",
    "Phosh.IdleDBusIdleMonitorProxy",
    "Phosh.IdleDBusIdleMonitorSkeleton",
    "Phosh.IdleDBusObjectManagerClient",
    "Phosh.IdleDBusObjectProxy",
    "Phosh.IdleDBusObjectSkeleton",
    "Phosh.IdleManager",
    "Phosh.KeyboardEvents",
    "Phosh.Keypad",
    "Phosh.LauncherEntryManager",
    "Phosh.LayoutManager",
    "Phosh.LocationInfo",
    "Phosh.LocationManager",
    "Phosh.LockscreenManager",
    "Phosh.Lockshield",
    "Phosh.MMDBusModemModem3gppProxy",
    "Phosh.MMDBusModemModem3gppSkeleton",
    "Phosh.MMDBusModemProxy",
    "Phosh.MMDBusModemSkeleton",
    "Phosh.MMDBusObjectManagerClient",
    "Phosh.MMDBusObjectProxy",
    "Phosh.MMDBusObjectSkeleton",
    "Phosh.Manager",
    "Phosh.MediaPlayer",
    "Phosh.ModeManager",
    "Phosh.Monitor",
    "Phosh.MonitorManager",
    "Phosh.MountManager",
    "Phosh.MountNotification",
    "Phosh.MountOperation",
    "Phosh.MprisDBusMediaPlayer2PlayerProxy",
    "Phosh.MprisDBusMediaPlayer2PlayerSkeleton",
    "Phosh.MprisDBusMediaPlayer2Proxy",
    "Phosh.MprisDBusMediaPlayer2Skeleton",
    "Phosh.NetworkAuthManager",
    "Phosh.NetworkAuthPrompt",
    "Phosh.Notification",
    "Phosh.NotificationBanner",
    "Phosh.NotificationContent",
    "Phosh.NotificationFrame",
    "Phosh.NotificationList",
    "Phosh.NotificationSource",
    "Phosh.NotifyDBusNotificationsProxy",
    "Phosh.NotifyDBusNotificationsSkeleton",
    "Phosh.NotifyFeedback",
    "Phosh.NotifyManager",
    "Phosh.OfonoDBusManagerProxy",
    "Phosh.OfonoDBusManagerSkeleton",
    "Phosh.OfonoDBusNetworkRegistrationProxy",
    "Phosh.OfonoDBusNetworkRegistrationSkeleton",
    "Phosh.OfonoDBusSimManagerProxy",
    "Phosh.OfonoDBusSimManagerSkeleton",
    "Phosh.OsdWindow",
    "Phosh.Osk0SmPuriOSK0Proxy",
    "Phosh.Osk0SmPuriOSK0Skeleton",
    "Phosh.OskButton",
    "Phosh.OskManager",
    "Phosh.Overview",
    "Phosh.PasswordEntry",
    "Phosh.PluginLoader",
    "Phosh.PolkitAuthAgent",
    "Phosh.PolkitAuthPrompt",
    "Phosh.PortalAccessManager",
    "Phosh.PortalRequest",
    "Phosh.PowerMenu",
    "Phosh.PowerMenuManager",
    "Phosh.Proximity",
    "Phosh.QuickSetting",
    "Phosh.RfkillDBusRfkillProxy",
    "Phosh.RfkillDBusRfkillSkeleton",
    "Phosh.RotateInfo",
    "Phosh.RotationManager",
    "Phosh.RunCommandDialog",
    "Phosh.RunCommandManager",
    "Phosh.ScreenSaverManager",
    "Phosh.ScreenshotManager",
    "Phosh.SensorProxyManager",
    "Phosh.SessionClientPrivateDBusClientPrivateProxy",
    "Phosh.SessionClientPrivateDBusClientPrivateSkeleton",
    "Phosh.SessionManager",
    "Phosh.SessionPresence",
    "Phosh.SessionPresenceDBusPresenceProxy",
    "Phosh.SessionPresenceDBusPresenceSkeleton",
    "Phosh.Splash",
    "Phosh.SplashManager",
    "Phosh.StatusPage",
    "Phosh.SuspendManager",
    "Phosh.SwipeAwayBin",
    "Phosh.SystemModal",
    "Phosh.SystemModalDialog",
    "Phosh.SystemPrompt",
    "Phosh.Thumbnail",
    "Phosh.TimestampLabel",
    "Phosh.TopPanel",
    "Phosh.Toplevel",
    "Phosh.ToplevelManager",
    "Phosh.ToplevelThumbnail",
    "Phosh.TorchInfo",
    "Phosh.TorchManager",
    "Phosh.VpnInfo",
    "Phosh.VpnManager",
    "Phosh.WWanInfo",
    "Phosh.WWanMM",
    "Phosh.WWanManager",
    "Phosh.WWanOfono",
    "Phosh.WWanStatusPage",
    "Phosh.Wayland",
    "Phosh.WidgetBox",
    "Phosh.WifiInfo",
    "Phosh.WifiManager",
    "Phosh.WifiNetwork",
    "Phosh.WifiStatusPage",
    # Ignore some classes with virtual functions where we also ignore the object types
    "Phosh.ThumbnailClass",
    "Phosh.ManagerClass",
    "Phosh.NotificationClass",
    "Phosh.DragSurfaceClass",
    # So we don't need to pull in gvc-mixer-control
    "Phosh.AudioDevicesClass",
    # This lack proper alignment as e.g. parents are missing	
    "Phosh.BackgroundManagerClass",
    "Phosh.BtManagerClass",
    "Phosh.CallsManagerClass",
    "Phosh.DBusNotificationClass",
    "Phosh.EmergencyCallsManagerClass",
    "Phosh.HomeClass",
    "Phosh.LauncherEntryManagerClass",
    "Phosh.ModeManagerClass",
    "Phosh.MountNotificationClass",
    "Phosh.SuspendManagerClass",
    "Phosh.TopPanelClass",
    "Phosh.ToplevelThumbnailClass",
    "Phosh.TorchManagerClass",
    # Ingore as we don't want to bother with libgnome-desktop
    "Phosh.BackgroundData",
    # Ingore as they use raw Wayland types
    "Phosh.WlBuffer",
    "Phosh.HeadMode",
    # Not actual types
    "Phosh.PhysicalSize",
    "Phosh.LogicalSize",
    # Not needed constants:
    "Phosh.ModeDeviceType",
]

[[object]]
name = "Phosh.WallClock"
status = "generate"
  [[object.function]]
  # We don't want to bother with libgnome-desktop
  name = "string_for_datetime"
  ignore = true

[[object]]
name = "Phosh.LayerSurface"
status = "generate"
# Ignore functions that return Wayland types for the moment
  [[object.function]]
  name = "get_wl_surface"
  ignore = true
  [[object.function]]
  name = "get_layer_surface"
  ignore = true
